smtp:
  address: <%= ENV.fetch('SES_SMTP_ENDPOINT', '') %>
  port: 587
  domain: 'staging.love-daddy.jp'
  authentication: :login
  user_name: <%= ENV.fetch('SES_SMTP_USER_NAME', '' ) %>
  password: <%= ENV.fetch('SES_SMTP_PASSWORD', '' ) %>

s3:
  access_key: <%= ENV.fetch('S3_ACCESS_KEY', '') %>
  secret_key: <%= ENV.fetch('S3_SECRET_KEY', '') %>
  region:     <%= ENV.fetch('S3_REGION', '') %>
  bucket:     <%= ENV.fetch('S3_BUCKET', '') %>
